#!/bin/bash
mv Administração-com-Gestão-da-Produção-Industrial__Bacharelado\ .md Administração-com-Gestão-da-Produção-Industrial__Bacharelado.md
mv Administração-com-Gestão-Financeira__Bacharelado\ .md Administração-com-Gestão-Financeira__Bacharelado.md
mv Administração-para-Bacharéis-em-Ciências-Contábeis__Bacharelado\ .md Administração-para-Bacharéis-em-Ciências-Contábeis__Bacharelado.md
mv Agronomia__Bacharelado\ .md Agronomia__Bacharelado.md
mv Análise-e-Desenvolvimento-de-Sistemas__Tecnólogo\ .md Análise-e-Desenvolvimento-de-Sistemas__Tecnólogo.md
mv Arquitetura-e-Urbanismo__Bacharelado\ .md Arquitetura-e-Urbanismo__Bacharelado.md
mv Arquitetura-e-Urbanismo-com-Controle-de-Obras__Bacharelado\ .md Arquitetura-e-Urbanismo-com-Controle-de-Obras__Bacharelado.md
mv Arquitetura-e-Urbanismo-para-Bacharéis-em-Engenheiro-Civil-__Bacharelado\ .md Arquitetura-e-Urbanismo-para-Bacharéis-em-Engenheiro-Civil-__Bacharelado.md
mv Artes-com-Processos-Educacionais__Licenciatura\ .md Artes-com-Processos-Educacionais__Licenciatura.md
mv Artes__Licenciatura\ .md Artes__Licenciatura.md
mv Automação-Industrial__Tecnólogo\ .md Automação-Industrial__Tecnólogo.md
mv Bacharel-em-Educação-Física-para-Licenciados-em-Educação-Física__Bacharelado\ .md Bacharel-em-Educação-Física-para-Licenciados-em-Educação-Física__Bacharelado.md
mv Banco-de-Dados__Tecnólogo\ .md Banco-de-Dados__Tecnólogo.md
mv Biomedicina__Bacharelado\ .md Biomedicina__Bacharelado.md
mv Biomedicina-com-Gestão-da-Qualidade-na-Saúde__Bacharelado\ .md Biomedicina-com-Gestão-da-Qualidade-na-Saúde__Bacharelado.md
mv Ciências-Biológicas-com-Processos-Educacionais__Licenciatura\ .md Ciências-Biológicas-com-Processos-Educacionais__Licenciatura.md
mv Ciências-Biológicas__Licenciatura\ .md Ciências-Biológicas__Licenciatura.md
mv Ciências-Contábeis__Bacharelado\ .md Ciências-Contábeis__Bacharelado.md
mv Ciências-Contábeis-com-Gestão-Financeira__Bacharelado\ .md Ciências-Contábeis-com-Gestão-Financeira__Bacharelado.md
mv Ciências-Contábeis-para-bacharéis-em-Administração__Bacharelado\ .md Ciências-Contábeis-para-bacharéis-em-Administração__Bacharelado.md
mv Ciências-da-Computação__Bacharelado\ .md Ciências-da-Computação__Bacharelado.md
mv Controle-de-Obras__Tecnólogo\ .md Controle-de-Obras__Tecnólogo.md
mv Economia__Bacharelado\ .md Economia__Bacharelado.md
mv Economia-com-Gestão-Financeira__Bacharelado\ .md Economia-com-Gestão-Financeira__Bacharelado.md
mv Educação-Especial-com-Processos-Educacionais__Licenciatura\ .md Educação-Especial-com-Processos-Educacionais__Licenciatura.md
mv Educação-Especial__Licenciatura\ .md Educação-Especial__Licenciatura.md
mv Educação-Física__Bacharelado\ .md Educação-Física__Bacharelado.md
mv Educação-Física-com-Processos-Educacionais__Licenciatura\ .md Educação-Física-com-Processos-Educacionais__Licenciatura.md
mv Educação-Física__Licenciatura\ .md Educação-Física__Licenciatura.md
mv Engenharia-Ambiental__Bacharelado\ .md Engenharia-Ambiental__Bacharelado.md
mv Engenharia-Civil__Bacharelado\ .md Engenharia-Civil__Bacharelado.md
mv Engenharia-Civil-com-Controle-de-Obras__Bacharelado\ .md Engenharia-Civil-com-Controle-de-Obras__Bacharelado.md
mv Engenharia-Civil-para-Bacharéis-em-Arquitetura-e-Urbanismo__Bacharelado\ .md Engenharia-Civil-para-Bacharéis-em-Arquitetura-e-Urbanismo__Bacharelado.md
mv Engenharia-da-Computação__Bacharelado\ .md Engenharia-da-Computação__Bacharelado.md
mv Engenharia-da-Produção__Bacharelado\ .md Engenharia-da-Produção__Bacharelado.md
mv Engenharia-da-Produção-com-Fabricação-Mecânica__Bacharelado\ .md Engenharia-da-Produção-com-Fabricação-Mecânica__Bacharelado.md
mv Engenharia-de-Software__Bacharelado\ .md Engenharia-de-Software__Bacharelado.md
mv Engenharia-de-Software-com-Análise-e-Desenv.-de-Sistemas__Bacharelado\ .md Engenharia-de-Software-com-Análise-e-Desenv.-de-Sistemas__Bacharelado.md
mv Engenharia-Elétrica__Bacharelado\ .md Engenharia-Elétrica__Bacharelado.md
mv Engenharia-Mecânica__Bacharelado\ .md Engenharia-Mecânica__Bacharelado.md
mv Engenharia-Mecânica-com-Fabricação-Mecânica__Bacharelado\ .md Engenharia-Mecânica-com-Fabricação-Mecânica__Bacharelado.md
mv Engenharia-Mecatrônica__Bacharelado\ .md Engenharia-Mecatrônica__Bacharelado.md
mv Engenharia-Mecatrônica-com-Fabricação-Mecânica__Bacharelado\ .md Engenharia-Mecatrônica-com-Fabricação-Mecânica__Bacharelado.md
mv Estética-e-Cosmética__Tecnólogo\ .md Estética-e-Cosmética__Tecnólogo.md
mv Fabricação-Mecânica__Tecnólogo\ .md Fabricação-Mecânica__Tecnólogo.md
mv Farmácia__Bacharelado\ .md Farmácia__Bacharelado.md
mv Farmácia-com-Gestão-da-Qualidade-na-Saúde__Bacharelado\ .md Farmácia-com-Gestão-da-Qualidade-na-Saúde__Bacharelado.md
mv Filosofia__Licenciatura\ .md Filosofia__Licenciatura.md
mv Física__Licenciatura\ .md Física__Licenciatura.md
mv Fisioterapia__Bacharelado\ .md Fisioterapia__Bacharelado.md
mv Fisioterapia-em-Gestão-da-Qualidade-na-Saúde__Bacharelado\ .md Fisioterapia-em-Gestão-da-Qualidade-na-Saúde__Bacharelado.md
mv Formação-Pedagógica-em-Licenciatura-em-História-para-Graduados__Licenciatura\ .md Formação-Pedagógica-em-Licenciatura-em-História-para-Graduados__Licenciatura.md
mv Formação-Pedagógica-em-Licenciatura-Letras-Português--Inglês-para-Graduados__Licenciatura\ .md Formação-Pedagógica-em-Licenciatura-Letras-Português--Inglês-para-Graduados__Licenciatura.md
mv Formação-Pedagógica-em-Licenciatura-Matemática-para-Graduados__Licenciatura\ .md Formação-Pedagógica-em-Licenciatura-Matemática-para-Graduados__Licenciatura.md
mv Gastronomia__Tecnólogo\ .md Gastronomia__Tecnólogo.md
mv Geografia-com-Processos-Educacionais__Licenciatura\ .md Geografia-com-Processos-Educacionais__Licenciatura.md
mv Geografia__Licenciatura\ .md Geografia__Licenciatura.md
mv Gestão-Comercial__Tecnólogo\ .md Gestão-Comercial__Tecnólogo.md
mv Gestão-da-Produção-Industrial__Tecnólogo\ .md Gestão-da-Produção-Industrial__Tecnólogo.md
mv Gestão-da-Qualidade-na-Saúde__Tecnólogo\ .md Gestão-da-Qualidade-na-Saúde__Tecnólogo.md
mv Gestão-da-Qualidade__Tecnólogo\ .md Gestão-da-Qualidade__Tecnólogo.md
mv Gestão-da-Segurança-Privada__Tecnólogo\ .md Gestão-da-Segurança-Privada__Tecnólogo.md
mv Gestão-da-Tecnologia-da-Informação__Tecnólogo\ .md Gestão-da-Tecnologia-da-Informação__Tecnólogo.md
mv Gestão-de-Recursos-Humanos__Tecnólogo\ .md Gestão-de-Recursos-Humanos__Tecnólogo.md
mv Gestão-do-Ambiental__Tecnólogo\ .md Gestão-do-Ambiental__Tecnólogo.md
mv Gestão-Financeira__Tecnólogo\ .md Gestão-Financeira__Tecnólogo.md
mv Gestão-Hospitalar__Tecnólogo\ .md Gestão-Hospitalar__Tecnólogo.md
mv Gestão-Pública__Tecnólogo\ .md Gestão-Pública__Tecnólogo.md
mv História-com-Processos-Educacionais__Licenciatura\ .md História-com-Processos-Educacionais__Licenciatura.md
mv História__Licenciatura\ .md História__Licenciatura.md
mv História-para-Licenciados__Licenciatura\ .md História-para-Licenciados__Licenciatura.md
mv Letras---Português--Inglês-com-Proc.-Educacionais__Licenciatura\ .md Letras---Português--Inglês-com-Proc.-Educacionais__Licenciatura.md
mv Letras---Português--Inglês__Licenciatura\ .md Letras---Português--Inglês__Licenciatura.md
mv Letras-Português--Inglês-para-Licenciados__Licenciatura\ .md Letras-Português--Inglês-para-Licenciados__Licenciatura.md
mv Letras---Português--Inglês---Português-Libras__Licenciatura\ .md Letras---Português--Inglês---Português-Libras__Licenciatura.md
mv Letras---Português-Libras-com-Proc.-Educacionais__Licenciatura\ .md Letras---Português-Libras-com-Proc.-Educacionais__Licenciatura.md
mv Letras---Português-Libras__Licenciatura\ .md Letras---Português-Libras__Licenciatura.md
mv Letras---Português__Licenciatura\ .md Letras---Português__Licenciatura.md
mv Logística__Tecnólogo\ .md Logística__Tecnólogo.md
mv Marketing-Digital__Tecnólogo\ .md Marketing-Digital__Tecnólogo.md
mv Marketing__Tecnólogo\ .md Marketing__Tecnólogo.md
mv Matemática-com-Processos-Educacionais__Licenciatura\ .md Matemática-com-Processos-Educacionais__Licenciatura.md
mv Matemática__Licenciatura\ .md Matemática__Licenciatura.md
mv Matemática-para-Licenciados__Licenciatura\ .md Matemática-para-Licenciados__Licenciatura.md
mv Mecatrônica-Industria__Tecnólogo\ .md Mecatrônica-Industria__Tecnólogo.md
mv Negócios-Imobiliários__Tecnólogo\ .md Negócios-Imobiliários__Tecnólogo.md
mv Nutrição__Bacharelado\ .md Nutrição__Bacharelado.md
mv Nutrição-com-Gestão-da-Qualidade-na-Saúde__Bacharelado\ .md Nutrição-com-Gestão-da-Qualidade-na-Saúde__Bacharelado.md
mv Pedagogia-com-Educação-Especial__Licenciatura\ .md Pedagogia-com-Educação-Especial__Licenciatura.md
mv Pedagogia-com-Processos-Educacionais__Licenciatura\ .md Pedagogia-com-Processos-Educacionais__Licenciatura.md
mv Pedagogia__Licenciatura\ .md Pedagogia__Licenciatura.md
mv Pedagogia-para-Licenciados__Licenciatura\ .md Pedagogia-para-Licenciados__Licenciatura.md
mv Processos-Educacionais__Tecnólogo\ .md Processos-Educacionais__Tecnólogo.md
mv Processos-Gerenciais__Tecnólogo\ .md Processos-Gerenciais__Tecnólogo.md
mv Produção-Industrial__Tecnólogo\ .md Produção-Industrial__Tecnólogo.md
mv Química__Licenciatura\ .md Química__Licenciatura.md
mv Redes-de-Computadores__Tecnólogo\ .md Redes-de-Computadores__Tecnólogo.md
mv Secretariado__Tecnólogo\ .md Secretariado__Tecnólogo.md
mv Segurança-Pública__Tecnólogo\ .md Segurança-Pública__Tecnólogo.md
mv Servicos-Juridicos__Tecnologo\ .md Servicos-Juridicos__Tecnologo.md
mv Serviço-Social__Bacharelado\ .md Serviço-Social__Bacharelado.md
mv Sistema-de-Informação__Bacharelado\ .md Sistema-de-Informação__Bacharelado.md
mv Sistema-de-Informação-com-Análise-e-Desenvolvimento-de-Sistemas__Bacharelado\ .md Sistema-de-Informação-com-Análise-e-Desenvolvimento-de-Sistemas__Bacharelado.md
mv Sociologia__Licenciatura\ .md Sociologia__Licenciatura.md
mv Tutoria-para-Educação-a-Distância__Tecnólogo\ .md Tutoria-para-Educação-a-Distância__Tecnólogo.md
